TAIS/urls.py
from django.contrib import admin
from django.urls import path, include
from chatbot.views import chatbot_list

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", chatbot_list, name="home"),
    path("api/", include("api.urls")),
    path("user/", include("user.urls")),
    path("gorevler/", include("gorevler.urls")),
    path("dokumanlar/", include("dokumanlar.urls")),
    path("notification/", include("notification.urls")),
    path("saas/", include("saas.urls")),
    path("chatbot/", include("chatbot.urls")),
    
]

api/urls.py
from django.urls import include, path
from rest_framework import routers
from api.views import GorevlerView, GorevlerDeatilView, GorevlerDeleteView, GorevlerUpdateView, GorevlerCreateView,check_activation_status


urlpatterns = [
    path('gorevler', GorevlerView.as_view(),name='gorevler'),
    path('gorevlerDetail/<int:id>', GorevlerDeatilView.as_view(),name='gorevler_detail'),
    path('gorevlerDelete/<int:id>', GorevlerDeleteView.as_view(),name='gorevler_delete'),
    path('gorevlerUpdate/<int:id>', GorevlerUpdateView.as_view(),name='gorevler_update'),
    path('gorevlerCreate', GorevlerCreateView.as_view(),name='gorevler_create'),
    
    path('check-activation-status/', check_activation_status, name='check_activation_status'),
]

gorevler/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name="gorevler"

urlpatterns = [
    path('ilkgorevEkle/',views.ilkgorevEkle,name='ilkgorevEkle'),
    path('gorevEkle/',views.gorevEkle,name='gorevEkle'),
    path('gorevSil/<int:id>',views.gorevSil,name='gorevSil'),
    path('gorevListele/<str:ap>',views.gorevListele,name='gorevListele'),
    path('gorevGoster/<int:id>',views.gorevGoster,name='gorevGoster'),
    path('gorevGuncelle/<int:id>',views.gorevGuncelle,name='gorevGuncelle'),
    path('taskViewWithSecret/<int:gorev_id>/<str:secret>',views.taskViewWithSecret,name='taskViewWithSecret'),
    path('gorevStatuUpdate/<int:gorev_id>/<int:statu_id>/<str:secret>',views.gorevStatuUpdate,name='gorevStatuUpdate'),

    path('duzenliGorevTanimla/',views.duzenliGorevTanimla,name='duzenliGorevTanimla'),
    path('duzenliGorevSil/<int:id>',views.duzenliGorevSil,name='duzenliGorevSil'),
    path('duzenliGorevListele/',views.duzenliGorevListele,name='duzenliGorevListele'),
    path('duzenliGorevGoster/<int:id>',views.duzenliGorevGoster,name='duzenliGorevGoster'),
    path('duzenliGorevGuncelle/<int:id>',views.duzenliGorevGuncelle,name='duzenliGorevGuncelle'),
    path('duzenliGorevRapor/<int:year>/<int:month>/<str:type>',views.duzenliGorevRapor,name='duzenliGorevRapor'),
    
    path('gorevStatuAdd/',views.gorevStatuAdd,name='gorevStatuAdd'),
    path('gorevStatuList/',views.gorevStatuList,name='gorevStatuList'),
    path('gorevStatuCustomUpdate/<int:id>',views.gorevStatuCustomUpdate,name='gorevStatuUpdate'),
    path('gorevStatuDelete/<int:id>',views.gorevStatuDelete,name='gorevStatuDelete'),


    path('gorevSmsGonder/<int:gorev_id>',views.gorevSmsGonder,name='gorevSmsGonder'),
    
    path('rapor_gorev/',views.rapor_gorev,name='rapor_gorev'),
    #path('acilan_gorev/',views.acilan_gorev,name='acilan_gorev'),
    path('gorev_takvim_data/',views.gorev_takvim_data,name='gorev_takvim_data'),
    path('takvim_task/',views.takvim_task,name='takvim_task'),
    
]

notification/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name="notification"

urlpatterns = [
    path('notificationAdd/',views.notificationAdd,name='notificationAdd'),
    #path('notificationDelete/<int:id>',views.notificationDelete,name='notificationDelete'),
    path('notificationList/',views.notificationList,name='notificationList'),
    #path('notificationView/<int:id>',views.notificationView,name='notificationView'),
    #path('notificationUpdate/<int:id>',views.notificationUpdate,name='notificationUpdate'),

    path('whatsappMessage/',views.whatsappMessage,name='whatsappMessage'),
    path('whatsappWebHook/',views.whatsappWebHook,name='whatsappWebHook'),
]

gorevler/models.py
from django.db import models
from user.models import User, Departments
from ckeditor.fields import RichTextField
from django.utils import timezone
from saas.models import Company
from user.models import Color
from django.utils.crypto import get_random_string
import datetime

# Create your models here.

class GorevType(models.Model):   # kontrol,standart,proje,revizyon
    id = models.AutoField(primary_key=True)
    type = models.CharField(max_length=30,verbose_name="Hatırlatma Tipi")
    aciklama = models.CharField(max_length=150,verbose_name="Açıklama",blank =True,null=True)
    created_date = models.DateTimeField(default=timezone.now,blank =True,null=True)
    company= models.ForeignKey(Company,on_delete=models.PROTECT,default=1)

    def __str__(self):
        return self.type
  
class DuzenliGorevTanim(models.Model):
    TEKRAR_TIPLERI = (
        ('1', 'Günlük'),
        ('2', 'Haftalık'),
        ('3', 'Aylık'),
        ('4', 'Yıllık'),
        ('5', 'Saatlik'),
    )

    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=150, verbose_name="Düzenli Görev Başlığı")
    description = RichTextField(verbose_name="Görev Detayları", blank=True, null=True)
    start_date = models.DateField(verbose_name="Başlangıç Tarihi",default=timezone.now)
    end_date = models.DateField(verbose_name="Bitiş Tarihi", blank=True, null=True)
    
    repeat_type = models.CharField(max_length=1, choices=TEKRAR_TIPLERI, default='1', verbose_name="Tekrar Tipi")
    frequency = models.IntegerField(default=1, verbose_name="Tekrar Sıklığı")
    days_of_week = models.JSONField(blank=True, null=True, verbose_name="Haftanın Günleri")
    days_of_month = models.JSONField(blank=True, null=True, verbose_name="Ayın Günleri")
    
    department = models.ForeignKey(Departments, verbose_name="Departman", null=True, blank=True, on_delete=models.SET_NULL)
    color = models.ForeignKey(Color, verbose_name="Renk", on_delete=models.SET_NULL, blank=True, null=True)
    created_date = models.DateTimeField(default=timezone.now)
    created_user = models.ForeignKey(User, verbose_name="Kaydı Açan",related_name="duzenliGorevCreatedUser",null=True,blank=True,on_delete=models.SET_NULL)
    responsible_user = models.ForeignKey(User,verbose_name="Görev Sorumlusu",related_name="duzenliGorevresUser",on_delete=models.PROTECT,null=True,blank=True)
    document = models.FileField(blank=True, null=True, verbose_name="Döküman (Varsa)")
    
    numberOfDayOpen = models.IntegerField(default=3, verbose_name="Açık Kalma Gün Sayısı")
    numberOfDayCreate = models.IntegerField(default=3, verbose_name="Kaç gün önce oluşturulacak")
    
    is_active = models.BooleanField(default=True, verbose_name="Aktif")
    
    company = models.ForeignKey(Company, on_delete=models.PROTECT, default=1)
    def __str__(self):
        return self.title
      
class GorevlerStatu (models.Model):
    id = models.AutoField(primary_key=True)
    statu = models.CharField(max_length=30,verbose_name="Gorev Statu")
    aciklama = models.CharField(max_length=150,verbose_name="Açıklama",blank =True,null=True)
    created_date = models.DateTimeField(default=timezone.now,blank =True,null=True)
    company= models.ForeignKey(Company,on_delete=models.PROTECT,default=1)
    color = models.ForeignKey(Color,verbose_name="Renk",on_delete=models.SET_NULL,blank=True,null=True)
    is_end = models.BooleanField(verbose_name="Görev Sonlandırma",default=False)
    is_start = models.BooleanField(verbose_name="Görev Başlatma",default=False)

    def __str__(self):
        return self.statu

class Gorevler (models.Model): 
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=150,verbose_name="Görev Başlığı")
    type = models.ForeignKey(GorevType,verbose_name="Görev Tipi",null=True,blank=True,on_delete=models.SET_NULL)
    scheduledTask = models.ForeignKey(DuzenliGorevTanim,verbose_name="Düzenli Görev",null=True,blank=True,on_delete=models.SET_NULL)    
    description = RichTextField(verbose_name="Görev Detayları",blank =True,null=True)
    solution = RichTextField(verbose_name="Tamamlama Özeti",blank =True,null=True)
    created_date =  models.DateTimeField(default=timezone.now)
    start_date = models.DateTimeField(verbose_name="Planlanan Başlangıç Tarihi",blank =True,null=True)
    deadline = models.DateTimeField(verbose_name="Planlanan Bitiş Tarihi",blank =True,null=True)
    open_user = models.ForeignKey(User, verbose_name="Kaydı Açan",related_name="openUser",null=True,blank=True,on_delete=models.SET_NULL)
    responsible_user = models.ForeignKey(User,verbose_name="Görev Sorumlusu",related_name="resUser",on_delete=models.PROTECT,null=True,blank=True)
    department = models.ForeignKey(Departments,verbose_name="Departman",null=True,blank=True,on_delete=models.SET_NULL)
    closed_date = models.DateTimeField(blank =True,null=True)
    dokuman = models.FileField(blank =True,null=True,verbose_name="Döküman")
    statu = models.ForeignKey(GorevlerStatu,default=1,null=True,blank=True,on_delete=models.SET_NULL)
    secret = models.CharField(max_length=50, verbose_name="Job secret")
    secret_expiredate = models.DateTimeField(blank =True,null=True,verbose_name="Secret Geçerlilik Tarihi")
    complete_level = models.IntegerField(default=0,verbose_name="Tamamlanma Oranı")
    harcama = models.FloatField(default=0,verbose_name="Harcama")
    company= models.ForeignKey(Company,on_delete=models.PROTECT,default=1)

    revision = models.IntegerField(verbose_name="Revizyon",default=1)
    res_user_name = models.CharField(verbose_name="Sorumlu Ad/Soyad",max_length=30,blank=True, null=True)
    res_user_telephone = models.CharField(verbose_name="Sorumlu kullanıcı telefonu",max_length=20,blank=True, null=True)
    res_user_email = models.CharField(verbose_name="Sorumlu kullanıcı email",max_length=20,blank=True, null=True)
    planed_startdate = models.DateField(blank=True, null=True)
    planed_date = models.DateField(blank=True, null=True)
    revision_date =models.DateTimeField(blank=True, null=True)

    latitude = models.FloatField(null=True, blank=True) 
    longitude = models.FloatField(null=True, blank=True) 
    priority = models.IntegerField(default=3) # 1-5 arasında öncelik puanı

    def save(self, *args, **kwargs):
        if not self.secret:
            self.secret = get_random_string(length=50).upper()
            self.secret_expiredate = timezone.now() + datetime.timedelta(days=7)
        if not self.created_date:
            self.created_date = timezone.now()

        super(Gorevler, self).save(*args, **kwargs)

class GorevNotu(models.Model):
    id = models.AutoField(primary_key=True)
    gorev = models.ForeignKey(Gorevler,verbose_name="gorev",on_delete=models.CASCADE)
    created_date = models.DateTimeField()
    open_user = models.ForeignKey(User, verbose_name="Kayıdı açan",null=True,blank=True,on_delete=models.SET_NULL)
    description = RichTextField(verbose_name="Açıklama",blank =True,null=True)
    dokuman = models.FileField(blank =True,null=True,verbose_name="Döküman")
    company= models.ForeignKey(Company,on_delete=models.PROTECT,default=1)

class ReminderType(models.Model):   # sms ,mail ,push notification ,app,web,whatsapp
    id = models.AutoField(primary_key=True)
    type = models.CharField(max_length=30,verbose_name="Hatırlatma Tipi")
    aciklama = models.CharField(max_length=150,verbose_name="Açıklama",blank =True,null=True)
    created_date = models.DateTimeField(default=timezone.now,blank =True,null=True)
    company= models.ForeignKey(Company,on_delete=models.PROTECT,default=1)

    def __str__(self):
        return self.type

class  Reminder(models.Model):
    zamanTipi = (
        ('1','Dakika'),
        ('2','Saat'),
        ('3','Gün'),
        ('4','Hafta'),
        ('5','Ay'),
    )
    id = models.AutoField(primary_key=True)
    gorev = models.ForeignKey(Gorevler,verbose_name="gorev",on_delete=models.CASCADE,blank=True,null=True)
    created_date = models.DateTimeField()
    open_user = models.ForeignKey(User, verbose_name="Kayıdı açan",null=True,blank=True,on_delete=models.SET_NULL)
    description = models.CharField(max_length=100,verbose_name="Hatırlatma Açıklaması",blank =True,null=True)
    reminder_date = models.DateTimeField(verbose_name="Hatırlatma Tarihi",null=True,blank=True)
    type = models.ForeignKey(ReminderType,verbose_name="Hatırlatma Tipi",null=True,blank=True,on_delete=models.SET_NULL)
    time = models.IntegerField(verbose_name="Ne kadar önceden hatırlatılsın",default=1)
    time_type = models.CharField(verbose_name="Saat / Gün / Hafta ...",max_length=1,choices=zamanTipi,default='3')
    company= models.ForeignKey(Company,on_delete=models.PROTECT,default=1)
    

gorevler/templates/email_notification_generic.html
<!DOCTYPE html>
<html>

<head>
    <title></title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <style type="text/css">
        body,
        table,
        td,
        a {
            -webkit-text-size-adjust: 100%;
            -ms-text-size-adjust: 100%;
        }

        table,
        td {
            mso-table-lspace: 0pt;
            mso-table-rspace: 0pt;
        }

        img {
            -ms-interpolation-mode: bicubic;
        }

        img {
            border: 0;
            height: auto;
            line-height: 100%;
            outline: none;
            text-decoration: none;
        }

        table {
            border-collapse: collapse !important;
        }

        body {
            height: 100% !important;
            margin: 0 !important;
            padding: 0 !important;
            width: 100% !important;
        }

        a[x-apple-data-detectors] {
            color: inherit !important;
            text-decoration: none !important;
            font-size: inherit !important;
            font-family: inherit !important;
            font-weight: inherit !important;
            line-height: inherit !important;
        }

        @media screen and (max-width: 480px) {
            .mobile-hide {
                display: none !important;
            }

            .mobile-center {
                text-align: center !important;
            }
        }

        div[style*="margin: 16px 0;"] {
            margin: 0 !important;
        }
    </style>

<body style="margin: 0 !important; padding: 0 !important; background-color: #eeeeee;" bgcolor="#eeeeee">
    <div style="display: none; font-size: 1px; color: #fefefe; line-height: 1px; font-family: Open Sans, Helvetica, Arial, sans-serif; max-height: 0px; max-width: 0px; opacity: 0; overflow: hidden;">
        
    </div>

 

    <table border="0" cellpadding="0" cellspacing="0" width="100%">
        <tr>
            <td align="center" style="background-color: #eeeeee;" bgcolor="#eeeeee">
                <table align="center" border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width:600px;">
                    <tr>
                        <td align="center" valign="top" style="font-size:0; padding: 35px;" bgcolor="#5499C7">
                            <div style="display:inline-block; max-width:50%; min-width:100px; vertical-align:top; width:100%;">
                                <table align="left" border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width:300px;">
                                    <tr>
                                        <td align="center" valign="top"  class="mobile-center">
                                            <a href="http://www.toyu.app" target="_blank" style="color: #ffffff; text-decoration: none;"><img src="https://toyu.app/wp-content/uploads/2023/06/cropped-TOYU-LOGO-V2-AMBLEM-YAZI-NEGATIVE.png" width="206" height="42" style="display: block; border: 0px;" /></a>
                                           
                                        </td>
                                    </tr>
                                </table>
                            </div>
                            
                        </td>
                    </tr>
                    <tr>
                        <td align="center" style="padding: 35px 35px 20px 35px; background-color: #ffffff;" bgcolor="#ffffff">
                            <table align="center" border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width:600px;">
                                <tr>
                                    <td align="center" style="font-family: Open Sans, Helvetica, Arial, sans-serif; font-size: 16px; font-weight: 400; line-height: 24px; padding-top: 25px;"> <img src="https://img.icons8.com/carbon-copy/100/000000/checked-checkbox.png" width="125" height="120" style="display: block; border: 0px;" /><br>
                                        <h2 style="font-size: 30px; font-weight: 800; line-height: 36px; color: #333333; margin: 0;"> Title </h2>
                                    </td>
                                </tr>
                                <tr>
                                    <td align="left" style="font-family: Open Sans, Helvetica, Arial, sans-serif; font-size: 16px; font-weight: 400; line-height: 24px; padding-top: 10px;">
                                        <p style="font-size: 16px; font-weight: 400; line-height: 24px; color: #777777;"> Açıklama </p>
                                    </td>
                                </tr>
                               
                            </table>
                        </td>
                    </tr>

                
                    <tr>
                        <td align="center" height="100%" valign="top" width="100%" style="padding: 0 35px 35px 35px; background-color: #ffffff;" bgcolor="#ffffff">
                            <table align="center" border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width:660px;">
                                <tr>
                                    <td align="center" valign="top" style="font-size:0;">
                                        <div style="display:inline-block; max-width:70%; min-width:240px; vertical-align:top; width:100%;">
                                            <table align="left" border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width:500px;">
                                                <tr>
                                                    <td align="left" valign="top" style="font-family: Open Sans, Helvetica, Arial, sans-serif; font-size: 16px; font-weight: 400; line-height: 24px;">
                                                       
                                                    </td>
                                                </tr>
                                            </table>
                                        </div>
                                        
                                    </td>
                                </tr>
                            </table>
                        </td>
                    </tr>
               
                    <tr>
                        <td align="center" style="padding: 35px; background-color: #5499C7;" bgcolor="#5499C7">
                            <table align="center" border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width:600px;">
                                <tr>
                                    <td align="center"> <img src="https://toyu.app/wp-content/uploads/2023/06/cropped-TOYU-LOGO-V2-AMBLEM-YAZI-NEGATIVE.png" width="85" height="70" style="display: block; border: 2px;" /> </td>
                                </tr>
                                
                                <tr>
                                    <td align="center" style="font-family: Open Sans, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: 400; line-height: 24px;">
                                        <p style="font-size: 14px; font-weight: 400; line-height: 20px; color: #ffffff;"> Bu uygulama TOYU tarafında geliştirildi <a href="http://www.toyu.app" target="_blank" style="color: #777777;">www.toyu.app</www></a>. </p>
                                    </td>
                                </tr>
                            </table>
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
</body>

</html>

gorevler/templates/gorevEkle.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}

<script>
    document.addEventListener("DOMContentLoaded", function () {
        const repeatTypeField = document.getElementById("id_repeat_type");
        const daysOfWeekField = document.getElementById("div_id_days_of_week");
        const daysOfMonthField = document.getElementById("div_id_days_of_month");
    
        function toggleFields() {
            if (repeatTypeField.value === "2") {
                daysOfWeekField.style.display = "block";
                daysOfMonthField.style.display = "none";
            } else if (repeatTypeField.value === "3") {
                daysOfWeekField.style.display = "none";
                daysOfMonthField.style.display = "block";
            } else {
                daysOfWeekField.style.display = "none";
                daysOfMonthField.style.display = "none";
            }
        }
    
        // Sayfa yüklendiğinde başlangıç durumunu kontrol et
        toggleFields();
    
        // repeat_type değiştiğinde alanları kontrol et
        repeatTypeField.addEventListener("change", toggleFields);
    });
    
</script>
<div class="row  m-2">
    <div >
        <br>
        <h3> Görev Ekle</h3>   
        <hr>
        
        <form method="post" enctype="multipart/form-data">
            {{ form.media }}
            {% csrf_token %}
            {{form|crispy }}
            {{formReminder|crispy }}
            
            <br>
            <button type="submit" class="btn btn-warning">Giriş</button>
        </form>
    </div>
</div>
{% endblock body %}

gorevler/templates/gorevGuncelle.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}
<div class="row">
    <div >
    <h3> 
            Görev Güncelle
            
    </h3>   
 
    <hr>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.media }}
        {{form|crispy }}
        <br>
        <button type="submit" class="btn btn-warning">Güncelle
            
        </button>
    </form>
</div>
{% endblock body %}

gorevler/templates/gorevStatuAdd.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}
<div class="row">
    <div >
    <h3> 
            Görev Statu EKLE
            
    </h3>   
 
    <hr>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.media }}
        {{form|crispy }}
        <br>
        <button type="submit" class="btn btn-warning">EKLE
            
        </button>
    </form>
</div>
{% endblock body %}

gorevler/templates/gorevStatuGuncelle.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}
<div class="row">
    <div >
    <h3> 
            Görev Statu Güncelle
            
    </h3>   
 
    <hr>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.media }}
        {{form|crispy }}
        <br>
        <button type="submit" class="btn btn-warning">Güncelle
            
        </button>
    </form>
</div>
{% endblock body %}

gorevler/templates/ilkGorevEkle.html
{% load static%}
{% load crispy_forms_tags %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <title>TOYU</title>
      <link rel="shortcut icon" href="{% static 'TEKNOLIKYA_icon.png' %}"/>
      <link rel="stylesheet" href="{% static 'assets/css/backend-plugin.min.css' %}">
      <link rel="stylesheet" href="{% static 'assets/css/backend.css' %}">
      <link rel="stylesheet" href="{% static 'assets/vendor/@fortawesome/fontawesome-free/css/all.min.css' %}">
      <link rel="stylesheet" href="{% static 'assets/vendor/line-awesome/dist/line-awesome/css/line-awesome.min.css' %}">
      <link rel="stylesheet" href="{% static 'assets/vendor/remixicon/fonts/remixicon.css' %}">  
      
      <script src="https://www.google.com/recaptcha/api.js" async defer></script>

      
      <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>

      <!--  recaptcha  için  view den site_key içinde public key gelmeli   -->
      <script src="https://www.google.com/recaptcha/api.js?render={{site_key}}"></script>
      <script>
         //global grecaptcha
         grecaptcha.ready(function() {
           grecaptcha.execute('{{site_key}}', {action: "/user/register/"}).then(function(token) {
             document.getElementById('g-recaptcha-response').value = token;
           });
         });
       </script>

   </head>

  <body class=" ">
    <!-- loader Start -->
    <div id="loading">
          <div id="loading-center">
          </div>
    </div>
    <!-- loader END -->
    
   {% if messages %}
      {% for message in messages %}
         <div {% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}> {{ message }} </div>
      {% endfor %}
   {% endif %}

      <script>
         // Sayfa yüklendiğinde modalı aç
         $(document).ready(function(){
            $("#myModal").modal('show');
         });
      </script>
      <div id="myModal" class="modal fade">
         <div class="modal-dialog modal-dialog-centered">
           <div class="modal-content">
           
             <!-- Modal Header -->
             <div class="modal-header">
               <h4 class="modal-title"> Demodan önce kısa bir eğitim</h4>
               <button type="button" class="close" data-dismiss="modal">&times;</button>
             </div>
             
             <!-- Modal Body -->
             <div class="modal-body">
               <p>İlk görevi birlikte belirleyelim. </p>
               <p>TOYU ile kolayca görev ataması yapabilirsiniz, aşağıdaki bilgileri doldurunuz ve kendinize iş açınız. </p>
             </div>
             
             <!-- Modal Footer -->
             <div class="modal-footer">
               <button type="button" class="btn btn-danger" data-dismiss="modal">Kapat</button>
             </div>
             
           </div>
         </div>
      </div>


      <div class="wrapper">
      <section class="login-content">
         <div class="container">
            <div class="row align-items-center justify-content-center height-self-center">
               <div class="col-lg-8">
                  <div class="card auth-card">
                     <div class="card-body p-0">
                        <div class="d-flex align-items-center auth-content">
                           <div class="col-lg-7 align-self-center">
                              <div class="p-2">
                                 <h2 class="mb-2">Görev Atama Ekranı</h2>
                                 <p>Aşağıdaki bilgileri doldurarak hızlıca bir görev ataması yapınız.</p>
                                 <form method="post" enctype="multipart/form-data">

                                    <div class="border p-2 rounded">
                                    
                                       <div id="div_id_title" class="form-group"> 
                                          <label for="id_title" class=" requiredField">
                                             Görev Sorumlusu<span class="asteriskField">*</span> </label> 
                                          <div> 
                                             <input type="text" name="title" placeholder="Kısa açıklama" maxlength="150" class="textinput textInput form-control" required="" id="id_title" value="{{user}}" disabled> 
                                             
                                          </div> 
                                       </div>


                                       {{ form.media }}
                                       {% csrf_token %}
                                       {{form|crispy }}
                                       <br>
                                       <button type="submit" class="btn btn-warning">Giriş</button>
                                    </div>
                                </form>
                              </div>
                           </div>
                           <div class="col-lg-5 content-right">
                              <img src="{% static 'TOYU_LOGO_V2_AMBLEM_YAZI.png' %}" class="img-fluid image-right" alt="">
                           </div>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </section>
      </div>
    
    <!-- Backend Bundle JavaScript -->
    <script src="{% static 'assets/js/backend-bundle.min.js' %}"></script>
    
    <!-- Table Treeview JavaScript -->
    <script src="{% static 'assets/js/table-treeview.js' %}"></script>
    
    <!-- Chart Custom JavaScript -->
    <script src="{% static 'assets/js/customizer.js' %}"></script>
    
    <!-- Chart Custom JavaScript -->
    <script async src="{% static 'assets/js/chart-custom.js' %}"></script>
    
    <!-- app JavaScript -->
    <script src="{% static 'assets/js/app.js' %}"></script>
  </body>
</html>